name: animangav4frontend
description: Proyecto destinado a la gestión de una apliación de venta de mangas.

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  bloc: ^8.1.1
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  http: ^0.13.5
  image_picker: ^0.8.4+9
  get_it: ^7.2.0
  injectable: ^2.1.0
  mime: ^1.0.1
  http_interceptor: ^1.0.1
  awesome_dialog: ^2.2.0
  shared_preferences: ^2.0.17
  flutter_neumorphic: ^3.0.0
  month_picker_dialog: ^2.0.2
  flutter_svg: ^1.0.3
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.3
  get_storage: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.3
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/
